### ISSUE TITLE
Feature Request: ability to add more sound effects.

### ISSUE THREAD

**Issue by fxnoob** [MahdiF/fartattack#1]
Hi @MahdiF ,
I was wondering to contribute by adding a feature which lets the user add their own sound effects. For instance, providing a setting option in which the user may use the pre-populated list or even have an option to add one.

Thoughts?

**Comment by MahdiF** [comment]
Hi @fxnoob thank you for your interest in improving the extension. However, I think it's better to keep the extension simple because most of the users will have limited time to play with the settings before their friends comes back to their computer and starts using it again.

With that said, I think your idea is pretty good and might be great for other extensions.

Thanks again for the suggestion @fxnoob .
